In [1]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_1 = _dntk.execute_sql(
  '',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_1

## Querying Entregas\_Julho\.csv with DataFrame SQL \(Preview\)

We'll use a DataFrame SQL block to read the CSV file located in the project root using the file path 'Entregas\_Julho\.csv'\. We'll select the ID, Data, and Tempo\_entrega columns and store the result as a query preview in a variable named entregas\_preview\. Query preview mode only materializes the first 100 rows and allows chaining the query later if needed\.

In [16]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

entregas_preview = _dntk.execute_sql(
  '-- Use quoted identifiers for file path table references in FROM clause per DuckDB\n-- Select only existing columns as requested\n-- No schema qualification needed for CSV scan via file path in DuckDB\nSELECT ID, Data, Tempo_entrega FROM \'Entregas_Julho.csv\';',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
entregas_preview

            ID       Data  Tempo_entrega
0            1 2025-07-01              4
1            2 2025-07-01             10
2            3 2025-07-01              7
3            4 2025-07-01              6
4            5 2025-07-01              2
...        ...        ...            ...
149997  149998 2025-07-30              2
149998  149999 2025-07-30              2
149999  150000 2025-07-30              4
150000    <NA>        NaT              0
150001    <NA>        NaT              0

[150002 rows x 3 columns]

### Convert the query preview to a pandas DataFrame and inspect the first 10 rows

In [3]:
# Convert the query preview to a pandas DataFrame and preview first 10 rows
entregas_df = entregas_preview
entregas_df.head(10)

   ID       Data  Tempo_entrega
0   1 2025-07-01              4
1   2 2025-07-01             10
2   3 2025-07-01              7
3   4 2025-07-01              6
4   5 2025-07-01              2
5   6 2025-07-01              2
6   7 2025-07-01              1
7   8 2025-07-01              9
8   9 2025-07-01              6
9  10 2025-07-01              7

In [4]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_3 = _dntk.execute_sql(
  'SELECT *\nFROM \'Entregas_Julho.csv\';\n',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_3

            ID       Data  Tempo_entrega Status_entrega        Regiao
0            1 2025-07-01              4       Entregue      Nordeste
1            2 2025-07-01             10       Entregue      Nordeste
2            3 2025-07-01              7        Em Rota      Nordeste
3            4 2025-07-01              6        Em Rota  Centro Oeste
4            5 2025-07-01              2        Em Rota  Centro Oeste
...        ...        ...            ...            ...           ...
149997  149998 2025-07-30              2        Em Rota         Norte
149998  149999 2025-07-30              2       Entregue       Sudeste
149999  150000 2025-07-30              4        Em Rota           Sul
150000    <NA>        NaT              0           None          None
150001    <NA>        NaT              0           None          None

[150002 rows x 5 columns]

In [5]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_4 = _dntk.execute_sql(
  'SELECT ID,Data, Tempo_entrega\nFROM \'Entregas_Julho.csv\'\nwhere Status_entrega = \'Entregue\'\n',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_4

           ID       Data  Tempo_entrega
0           1 2025-07-01              4
1           2 2025-07-01             10
2           8 2025-07-01              9
3           9 2025-07-01              6
4          10 2025-07-01              7
...       ...        ...            ...
89743  149990 2025-07-30              8
89744  149992 2025-07-30              2
89745  149994 2025-07-30              2
89746  149996 2025-07-30              2
89747  149999 2025-07-30              2

[89748 rows x 3 columns]

In [6]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_5 = _dntk.execute_sql(
  'SELECT ID, Status_entrega\nFROM "Entregas_Julho.csv"\nWHERE Status_entrega <> \'Entregue\';',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_5

           ID Status_entrega
0           3        Em Rota
1           4        Em Rota
2           5        Em Rota
3           6       Pendente
4           7       Pendente
...       ...            ...
60247  149993        Em Rota
60248  149995        Em Rota
60249  149997        Em Rota
60250  149998        Em Rota
60251  150000        Em Rota

[60252 rows x 2 columns]

In [7]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_6 = _dntk.execute_sql(
  'SELECT ID, Tempo_entrega\nFROM "Entregas_Julho.csv"\nWHERE Tempo_entrega > 5;\n',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_6

           ID  Tempo_entrega
0           2             10
1           3              7
2           4              6
3           8              9
4           9              6
...       ...            ...
67668  149989              8
67669  149990              8
67670  149991              7
67671  149993              9
67672  149995              7

[67673 rows x 2 columns]

In [8]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_7 = _dntk.execute_sql(
  'SELECT ID, Status_entrega, Tempo_entrega\nFROM \'Entregas_Julho.csv\'\nWHERE Status_entrega = \'Entregue\' AND Tempo_entrega > 5;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_7

           ID Status_entrega  Tempo_entrega
0           2       Entregue             10
1           8       Entregue              9
2           9       Entregue              6
3          10       Entregue              7
4          12       Entregue             10
...       ...            ...            ...
40697  149973       Entregue              9
40698  149974       Entregue              9
40699  149986       Entregue              9
40700  149987       Entregue              8
40701  149990       Entregue              8

[40702 rows x 3 columns]

In [9]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{"sortBy":[],"filters":[],"pageSize":10,"pageIndex":14,"columnOrder":["ID","Status_entrega","Data"],"hiddenColumnIds":[],"columnDisplayNames":[],"conditionalFilters":[],"cellFormattingRules":[],"wrappedTextColumnIds":[]}')
else:
  _deepnote_current_table_attrs = '{"sortBy":[],"filters":[],"pageSize":10,"pageIndex":14,"columnOrder":["ID","Status_entrega","Data"],"hiddenColumnIds":[],"columnDisplayNames":[],"conditionalFilters":[],"cellFormattingRules":[],"wrappedTextColumnIds":[]}'

df_8 = _dntk.execute_sql(
  'SELECT ID, Status_entrega, Data\nFROM \'Entregas_Julho.csv\'\nwhere Status_entrega = \'Pendente\' OR Status_entrega =\'Em Rota\';',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_8

           ID Status_entrega       Data
0           3        Em Rota 2025-07-01
1           4        Em Rota 2025-07-01
2           5        Em Rota 2025-07-01
3           6       Pendente 2025-07-01
4           7       Pendente 2025-07-01
...       ...            ...        ...
60247  149993        Em Rota 2025-07-30
60248  149995        Em Rota 2025-07-30
60249  149997        Em Rota 2025-07-30
60250  149998        Em Rota 2025-07-30
60251  150000        Em Rota 2025-07-30

[60252 rows x 3 columns]

In [10]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_9 = _dntk.execute_sql(
  'SELECT ID, Status_entrega, Tempo_entrega\nFROM \'Entregas_Julho.csv\'\nWHERE (Status_entrega = \'PENDENTE\' AND Tempo_entrega > 5)\nOR (Status_entrega = \'Em Rota\' AND Tempo_entrega > 3);',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_9

           ID Status_entrega  Tempo_entrega
0           3        Em Rota              7
1           4        Em Rota              6
2          13        Em Rota              8
3          19        Em Rota              4
4          25        Em Rota              5
...       ...            ...            ...
29274  149989        Em Rota              8
29275  149991        Em Rota              7
29276  149993        Em Rota              9
29277  149995        Em Rota              7
29278  150000        Em Rota              4

[29279 rows x 3 columns]

In [11]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_10 = _dntk.execute_sql(
  'SELECT ID, Regiao, Status_entrega\nFROM \'Entregas_Julho.csv\'\nWHERE Regiao IN (\'Sul\', \'Sudeste\', \'Nordeste\');',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_10

           ID    Regiao Status_entrega
0           1  Nordeste       Entregue
1           2  Nordeste       Entregue
2           3  Nordeste        Em Rota
3           6   Sudeste       Pendente
4           8  Nordeste       Entregue
...       ...       ...            ...
89994  149995  Nordeste        Em Rota
89995  149996  Nordeste       Entregue
89996  149997   Sudeste        Em Rota
89997  149999   Sudeste       Entregue
89998  150000       Sul        Em Rota

[89999 rows x 3 columns]

In [12]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{"sortBy":[],"filters":[],"pageSize":10,"pageIndex":0,"columnOrder":["ID","Regiao"],"hiddenColumnIds":[],"columnDisplayNames":[],"conditionalFilters":[],"cellFormattingRules":[],"wrappedTextColumnIds":[]}')
else:
  _deepnote_current_table_attrs = '{"sortBy":[],"filters":[],"pageSize":10,"pageIndex":0,"columnOrder":["ID","Regiao"],"hiddenColumnIds":[],"columnDisplayNames":[],"conditionalFilters":[],"cellFormattingRules":[],"wrappedTextColumnIds":[]}'

df_11 = _dntk.execute_sql(
  'SELECT ID, Regiao\nFROM \'Entregas_Julho.csv\'\nwhere Regiao NOT IN(\'Norte\', \'Centro Oeste\');',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_11

           ID    Regiao
0           1  Nordeste
1           2  Nordeste
2           3  Nordeste
3           6   Sudeste
4           8  Nordeste
...       ...       ...
89994  149995  Nordeste
89995  149996  Nordeste
89996  149997   Sudeste
89997  149999   Sudeste
89998  150000       Sul

[89999 rows x 2 columns]

In [34]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_12 = _dntk.execute_sql(
  'SELECT ID, Regiao\nFROM \'Entregas_Julho.csv\'\nWHERE Regiao IN (\n    SELECT Regiao\n    FROM \'Tabela_Rotas.csv\'\n    WHERE Entrega_Expressa = \'SIM\'\n);',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_12

            ID        Regiao
0            1      Nordeste
1            2      Nordeste
2            3      Nordeste
3            4  Centro Oeste
4            5  Centro Oeste
...        ...           ...
149995  149996      Nordeste
149996  149997       Sudeste
149997  149998         Norte
149998  149999       Sudeste
149999  150000           Sul

[150000 rows x 2 columns]

In [61]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_13 = _dntk.execute_sql(
  'SELECT ID, Tempo_Entrega, Status_entrega\nFROM \'Entregas_Julho.csv\'\nWHERE Tempo_Entrega > 2 \nAND (Status_entrega = \'Pendente\' OR Status_entrega = \'Em Rota\') \nAND Regiao\n IN(\n    SELECT Regiao\n    FROM \'Regioes_certificadas.csv\'\n);',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_13

           ID  Tempo_entrega Status_entrega
0           3              7        Em Rota
1          25              5        Em Rota
2          28              5        Em Rota
3          31              6        Em Rota
4          45              3        Em Rota
...       ...            ...            ...
18001  149975              9        Em Rota
18002  149983              4        Em Rota
18003  149989              8        Em Rota
18004  149991              7        Em Rota
18005  149995              7        Em Rota

[18006 rows x 3 columns]

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=e64f4dab-672d-4396-a9cf-e4e0f8546c70' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' />
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>